export const MOCKDATA: Employee[] = [
  {
    id: 1,
    firstname: "Pò",
    lastname: "Blaxall",
    state: "Île-de-France",
    street: "Walton",
    city: "Cergy-Pontoise",
    zip: "95021 CEDEX",
    birthDate: "25-11-2017",
    jobStartDate: "26-05-2024",
    service: "Tax Accountant",
  },
  {
    id: 2,
    firstname: "Fèi",
    lastname: "Pennoni",
    state: "Bretagne",
    street: "Atwood",
    city: "Landivisiau",
    zip: "29404 CEDEX",
    birthDate: "27-03-2015",
    jobStartDate: "08-09-2023",
    service: "Software Consultant",
  },
  {
    id: 3,
    firstname: "Aimée",
    lastname: "Bontein",
    state: "Aquitaine",
    street: "Luster",
    city: "Bayonne",
    zip: "64185 CEDEX",
    birthDate: "26-08-2023",
    jobStartDate: "17-12-2023",
    service: "Research Assistant IV",
  },
  {
    id: 4,
    firstname: "Esbjörn",
    lastname: "Crabbe",
    state: "Provence-Alpes-Côte d'Azur",
    street: "Northport",
    city: "Marseille",
    zip: "13348 CEDEX 20",
    birthDate: "06-01-2017",
    jobStartDate: "03-01-2024",
    service: "Professor",
  },
  {
    id: 5,
    firstname: "Rachèle",
    lastname: "Bitten",
    state: "Champagne-Ardenne",
    street: "Waxwing",
    city: "Langres",
    zip: "52204 CEDEX",
    birthDate: "15-10-2014",
    jobStartDate: "22-05-2024",
    service: "Recruiter",
  },
  {
    id: 6,
    firstname: "Lorène",
    lastname: "Simnor",
    state: "Basse-Normandie",
    street: "Everett",
    city: "Caen",
    zip: "14097 CEDEX 9",
    birthDate: "08-01-2013",
    jobStartDate: "19-08-2024",
    service: "Marketing Assistant",
  },
  {
    id: 7,
    firstname: "Régine",
    lastname: "Manning",
    state: "Île-de-France",
    street: "Dorton",
    city: "Goussainville",
    zip: "95194 CEDEX",
    birthDate: "16-01-2018",
    jobStartDate: "15-07-2024",
    service: "Chemical Engineer",
  },
  {
    id: 8,
    firstname: "Naéva",
    lastname: "Hannaway",
    state: "Île-de-France",
    street: "Maple",
    city: "Bagnolet",
    zip: "93175 CEDEX",
    birthDate: "25-11-2016",
    jobStartDate: "13-09-2023",
    service: "Senior Editor",
  },
  {
    id: 9,
    firstname: "Léana",
    lastname: "Woodroffe",
    state: "Aquitaine",
    street: "Ramsey",
    city: "Floirac",
    zip: "33274 CEDEX",
    birthDate: "24-05-2016",
    jobStartDate: "29-12-2023",
    service: "Programmer IV",
  },
  {
    id: 10,
    firstname: "Mårten",
    lastname: "Webber",
    state: "Bourgogne",
    street: "Truax",
    city: "Nuits-Saint-Georges",
    zip: "21704 CEDEX",
    birthDate: "19-03-2022",
    jobStartDate: "19-02-2024",
    service: "Teacher",
  },
  {
    id: 11,
    firstname: "Torbjörn",
    lastname: "Barbosa",
    state: "Île-de-France",
    street: "Sachtjen",
    city: "Antony",
    zip: "92762 CEDEX",
    birthDate: "04-09-2020",
    jobStartDate: "09-03-2024",
    service: "Physical Therapy Assistant",
  },
  {
    id: 12,
    firstname: "Anaël",
    lastname: "Langrish",
    state: "Martinique",
    street: "Knutson",
    city: "Fort-de-France",
    zip: "97265 CEDEX",
    birthDate: "03-08-2016",
    jobStartDate: "11-02-2024",
    service: "Structural Analysis Engineer",
  },
  {
    id: 13,
    firstname: "Mélanie",
    lastname: "Loft",
    state: "Île-de-France",
    street: "Reinke",
    city: "Colombes",
    zip: "92715 CEDEX",
    birthDate: "25-12-2016",
    jobStartDate: "21-10-2023",
    service: "Senior Cost Accountant",
  },
  {
    id: 14,
    firstname: "Fèi",
    lastname: "Espinoy",
    state: "Île-de-France",
    street: "Glacier Hill",
    city: "Rungis",
    zip: "94659 CEDEX 1",
    birthDate: "04-03-2017",
    jobStartDate: "21-05-2024",
    service: "Account Executive",
  },
  {
    id: 15,
    firstname: "Marie-josée",
    lastname: "Wardingley",
    state: "Île-de-France",
    street: "Dahle",
    city: "Saint-Gratien",
    zip: "95219 CEDEX",
    birthDate: "27-06-2020",
    jobStartDate: "04-07-2024",
    service: "Help Desk Operator",
  },
  {
    id: 16,
    firstname: "Styrbjörn",
    lastname: "Ricard",
    state: "Basse-Normandie",
    street: "Lindbergh",
    city: "Argentan",
    zip: "61891 CEDEX 9",
    birthDate: "28-09-2015",
    jobStartDate: "08-09-2023",
    service: "Electrical Engineer",
  },
  {
    id: 17,
    firstname: "Loïc",
    lastname: "Doles",
    state: "Provence-Alpes-Côte d'Azur",
    street: "Pennsylvania",
    city: "Marseille",
    zip: "13907 CEDEX 20",
    birthDate: "30-06-2017",
    jobStartDate: "06-05-2024",
    service: "Staff Accountant I",
  },
  {
    id: 18,
    firstname: "Eliès",
    lastname: "Minmagh",
    state: "Provence-Alpes-Côte d'Azur",
    street: "Del Sol",
    city: "Puget-sur-Argens",
    zip: "83484 CEDEX",
    birthDate: "25-01-2015",
    jobStartDate: "16-10-2023",
    service: "Assistant Professor",
  },
  {
    id: 19,
    firstname: "Rachèle",
    lastname: "Vasilyev",
    state: "Île-de-France",
    street: "Holmberg",
    city: "Corbeil-Essonnes",
    zip: "91104 CEDEX",
    birthDate: "01-12-2019",
    jobStartDate: "26-08-2024",
    service: "Social Worker",
  },
  {
    id: 20,
    firstname: "Hélène",
    lastname: "Pingston",
    state: "Bretagne",
    street: "Helena",
    city: "Vannes",
    zip: "56004 CEDEX",
    birthDate: "14-05-2022",
    jobStartDate: "11-07-2024",
    service: "Quality Control Specialist",
  },
  {
    id: 21,
    firstname: "Märta",
    lastname: "Duffy",
    state: "Île-de-France",
    street: "Kropf",
    city: "Marne-la-Vallée",
    zip: "77602 CEDEX 3",
    birthDate: "18-01-2021",
    jobStartDate: "08-01-2024",
    service: "Graphic Designer",
  },
  {
    id: 22,
    firstname: "Dà",
    lastname: "Moreside",
    state: "Provence-Alpes-Côte d'Azur",
    street: "Debra",
    city: "Marseille",
    zip: "13937 CEDEX 20",
    birthDate: "04-12-2023",
    jobStartDate: "18-11-2023",
    service: "Research Associate",
  },
  {
    id: 23,
    firstname: "Liè",
    lastname: "Macvain",
    state: "Provence-Alpes-Côte d'Azur",
    street: "Hansons",
    city: "Marseille",
    zip: "13343 CEDEX 15",
    birthDate: "18-09-2021",
    jobStartDate: "19-01-2024",
    service: "Administrative Assistant I",
  },
  {
    id: 24,
    firstname: "Zhì",
    lastname: "Gorcke",
    state: "Île-de-France",
    street: "Gale",
    city: "Cergy-Pontoise",
    zip: "95652 CEDEX",
    birthDate: "23-03-2014",
    jobStartDate: "29-09-2023",
    service: "Geologist IV",
  },
  {
    id: 25,
    firstname: "Océane",
    lastname: "Lansly",
    state: "Île-de-France",
    street: "Scofield",
    city: "Bondy",
    zip: "93144 CEDEX",
    birthDate: "17-07-2014",
    jobStartDate: "17-08-2024",
    service: "Help Desk Technician",
  },
  {
    id: 26,
    firstname: "Annotés",
    lastname: "McKean",
    state: "Provence-Alpes-Côte d'Azur",
    street: "Dwight",
    city: "Marseille",
    zip: "13269 CEDEX 08",
    birthDate: "23-06-2017",
    jobStartDate: "18-05-2024",
    service: "Systems Administrator III",
  },
  {
    id: 27,
    firstname: "Cléopatre",
    lastname: "Hawes",
    state: "Aquitaine",
    street: "Mockingbird",
    city: "Périgueux",
    zip: "24053 CEDEX",
    birthDate: "24-04-2021",
    jobStartDate: "01-01-2024",
    service: "Senior Editor",
  },
  {
    id: 28,
    firstname: "Loïs",
    lastname: "Maevela",
    state: "Nord-Pas-de-Calais",
    street: "Kensington",
    city: "Armentières",
    zip: "59425 CEDEX",
    birthDate: "12-12-2015",
    jobStartDate: "29-07-2024",
    service: "Administrative Assistant IV",
  },
  {
    id: 29,
    firstname: "Maëlle",
    lastname: "Mylchreest",
    state: "Île-de-France",
    street: "Toban",
    city: "Meaux",
    zip: "77104 CEDEX",
    birthDate: "23-08-2021",
    jobStartDate: "11-02-2024",
    service: "Media Manager IV",
  },
  {
    id: 30,
    firstname: "Adèle",
    lastname: "Croizier",
    state: "Bourgogne",
    street: "Sunfield",
    city: "Mâcon",
    zip: "71009 CEDEX",
    birthDate: "25-01-2013",
    jobStartDate: "17-10-2023",
    service: "Product Engineer",
  },
  {
    id: 31,
    firstname: "Clémentine",
    lastname: "Shelp",
    state: "Île-de-France",
    street: "Talmadge",
    city: "Mantes-la-Jolie",
    zip: "78718 CEDEX",
    birthDate: "10-05-2022",
    jobStartDate: "09-07-2024",
    service: "Help Desk Operator",
  },
  {
    id: 32,
    firstname: "Ophélie",
    lastname: "Tilson",
    state: "Île-de-France",
    street: "Forest Dale",
    city: "Paris 12",
    zip: "75609 CEDEX 12",
    birthDate: "08-06-2017",
    jobStartDate: "23-02-2024",
    service: "Research Associate",
  },
  {
    id: 33,
    firstname: "Maëline",
    lastname: "Darrigoe",
    state: "Champagne-Ardenne",
    street: "Schurz",
    city: "Reims",
    zip: "51064 CEDEX",
    birthDate: "29-08-2017",
    jobStartDate: "02-12-2023",
    service: "Senior Sales Associate",
  },
  {
    id: 34,
    firstname: "Åslög",
    lastname: "Arington",
    state: "Île-de-France",
    street: "Esker",
    city: "Paris 13",
    zip: "75643 CEDEX 13",
    birthDate: "10-11-2014",
    jobStartDate: "26-08-2024",
    service: "Web Designer I",
  },
  {
    id: 35,
    firstname: "Yóu",
    lastname: "Bernaldez",
    state: "Haute-Normandie",
    street: "Anhalt",
    city: "Rouen",
    zip: "76177 CEDEX",
    birthDate: "08-12-2023",
    jobStartDate: "19-11-2023",
    service: "Occupational Therapist",
  },
  {
    id: 36,
    firstname: "Örjan",
    lastname: "Eastwell",
    state: "Île-de-France",
    street: "Golf View",
    city: "Orsay",
    zip: "91893 CEDEX",
    birthDate: "29-03-2013",
    jobStartDate: "23-07-2024",
    service: "Food Chemist",
  },
  {
    id: 37,
    firstname: "Maëlann",
    lastname: "Gosnay",
    state: "Champagne-Ardenne",
    street: "Buena Vista",
    city: "Charleville-Mézières",
    zip: "08013 CEDEX",
    birthDate: "08-09-2019",
    jobStartDate: "10-11-2023",
    service: "Accounting Assistant III",
  },
  {
    id: 38,
    firstname: "Géraldine",
    lastname: "Verheijden",
    state: "Centre",
    street: "Schurz",
    city: "Orléans",
    zip: "45947 CEDEX 9",
    birthDate: "29-06-2015",
    jobStartDate: "05-02-2024",
    service: "Editor",
  },
  {
    id: 39,
    firstname: "Maï",
    lastname: "Well",
    state: "Franche-Comté",
    street: "Bunker Hill",
    city: "Besançon",
    zip: "25004 CEDEX",
    birthDate: "19-10-2012",
    jobStartDate: "28-03-2024",
    service: "Nurse Practicioner",
  },
  {
    id: 40,
    firstname: "Nuó",
    lastname: "Warbys",
    state: "Nord-Pas-de-Calais",
    street: "Cody",
    city: "Lille",
    zip: "59044 CEDEX",
    birthDate: "11-03-2023",
    jobStartDate: "22-03-2024",
    service: "Community Outreach Specialist",
  },
  {
    id: 41,
    firstname: "Mélia",
    lastname: "Donnellan",
    state: "Bretagne",
    street: "Northfield",
    city: "Auray",
    zip: "56404 CEDEX",
    birthDate: "02-12-2022",
    jobStartDate: "20-12-2023",
    service: "Legal Assistant",
  },
  {
    id: 42,
    firstname: "Nuó",
    lastname: "Beininck",
    state: "Limousin",
    street: "Bowman",
    city: "Limoges",
    zip: "87077 CEDEX 9",
    birthDate: "23-12-2022",
    jobStartDate: "28-01-2024",
    service: "Chemical Engineer",
  },
  {
    id: 43,
    firstname: "Mégane",
    lastname: "Mourgue",
    state: "Île-de-France",
    street: "Transport",
    city: "Paris La Défense",
    zip: "92077 CEDEX",
    birthDate: "15-04-2016",
    jobStartDate: "16-05-2024",
    service: "Information Systems Manager",
  },
  {
    id: 44,
    firstname: "Magdalène",
    lastname: "Beat",
    state: "Île-de-France",
    street: "Orin",
    city: "Paris 13",
    zip: "75638 CEDEX 13",
    birthDate: "26-12-2020",
    jobStartDate: "07-02-2024",
    service: "Teacher",
  },
  {
    id: 45,
    firstname: "Rébecca",
    lastname: "Sevitt",
    state: "Aquitaine",
    street: "Northwestern",
    city: "Pau",
    zip: "64044 CEDEX",
    birthDate: "30-12-2014",
    jobStartDate: "15-12-2023",
    service: "Internal Auditor",
  },
  {
    id: 46,
    firstname: "Clélia",
    lastname: "Cromett",
    state: "Bretagne",
    street: "Oak Valley",
    city: "Locminé",
    zip: "56504 CEDEX",
    birthDate: "13-08-2015",
    jobStartDate: "14-05-2024",
    service: "Senior Financial Analyst",
  },
  {
    id: 47,
    firstname: "Salomé",
    lastname: "Howley",
    state: "Champagne-Ardenne",
    street: "Fairview",
    city: "Reims",
    zip: "51064 CEDEX",
    birthDate: "06-05-2017",
    jobStartDate: "17-05-2024",
    service: "Actuary",
  },
  {
    id: 48,
    firstname: "Noëlla",
    lastname: "Slisby",
    state: "İstanbul",
    street: "Golden Leaf",
    city: "Merkezköy",
    zip: "34829",
    birthDate: "21-02-2021",
    jobStartDate: "14-02-2024",
    service: "Software Engineer II",
  },
  {
    id: 49,
    firstname: "Réservés",
    lastname: "Le Brum",
    state: "Bretagne",
    street: "Elgar",
    city: "Rennes",
    zip: "35009 CEDEX",
    birthDate: "09-03-2017",
    jobStartDate: "15-01-2024",
    service: "Senior Quality Engineer",
  },
  {
    id: 50,
    firstname: "Kuí",
    lastname: "Featherston",
    state: "Franche-Comté",
    street: "Union",
    city: "Montbéliard",
    zip: "25204 CEDEX",
    birthDate: "11-01-2018",
    jobStartDate: "23-02-2024",
    service: "Media Manager III",
  },
  {
    id: 51,
    firstname: "Maëlle",
    lastname: "Tremmel",
    state: "Île-de-France",
    street: "Becker",
    city: "Bobigny",
    zip: "93737 CEDEX 9",
    birthDate: "26-04-2018",
    jobStartDate: "28-12-2023",
    service: "Internal Auditor",
  },
  {
    id: 52,
    firstname: "Marie-françoise",
    lastname: "Cariss",
    state: "Franche-Comté",
    street: "Butterfield",
    city: "Baume-les-Dames",
    zip: "25117 CEDEX",
    birthDate: "25-10-2015",
    jobStartDate: "22-07-2024",
    service: "Pharmacist",
  },
  {
    id: 53,
    firstname: "Mylène",
    lastname: "Hadcock",
    state: "Île-de-France",
    street: "East",
    city: "Paris 17",
    zip: "75832 CEDEX 17",
    birthDate: "28-06-2022",
    jobStartDate: "19-10-2023",
    service: "Internal Auditor",
  },
  {
    id: 54,
    firstname: "Françoise",
    lastname: "Fayers",
    state: "Aquitaine",
    street: "Myrtle",
    city: "Agen",
    zip: "47912 CEDEX 9",
    birthDate: "26-03-2015",
    jobStartDate: "21-09-2023",
    service: "Geological Engineer",
  },
  {
    id: 55,
    firstname: "Réjane",
    lastname: "Scrooby",
    state: "Basse-Normandie",
    street: "Lien",
    city: "Flers",
    zip: "61104 CEDEX",
    birthDate: "31-10-2023",
    jobStartDate: "05-08-2024",
    service: "Internal Auditor",
  },
  {
    id: 56,
    firstname: "Solène",
    lastname: "Jorissen",
    state: "Île-de-France",
    street: "Pepper Wood",
    city: "Versailles",
    zip: "78014 CEDEX",
    birthDate: "09-03-2024",
    jobStartDate: "09-09-2023",
    service: "Software Test Engineer I",
  },
  {
    id: 57,
    firstname: "Dorothée",
    lastname: "De Francisci",
    state: "Île-de-France",
    street: "Mallory",
    city: "Saint-Quentin-en-Yvelines",
    zip: "78925 CEDEX 9",
    birthDate: "07-08-2023",
    jobStartDate: "23-12-2023",
    service: "Safety Technician II",
  },
  {
    id: 58,
    firstname: "Estève",
    lastname: "Schoular",
    state: "Bourgogne",
    street: "4th",
    city: "Dijon",
    zip: "21051 CEDEX",
    birthDate: "17-11-2018",
    jobStartDate: "13-03-2024",
    service: "Operator",
  },
  {
    id: 59,
    firstname: "Adélie",
    lastname: "Kahn",
    state: "Centre",
    street: "New Castle",
    city: "Fleury-les-Aubrais",
    zip: "45404 CEDEX",
    birthDate: "11-02-2015",
    jobStartDate: "06-12-2023",
    service: "Operator",
  },
  {
    id: 60,
    firstname: "Magdalène",
    lastname: "Biasio",
    state: "Franche-Comté",
    street: "Jana",
    city: "Besançon",
    zip: "25004 CEDEX",
    birthDate: "07-03-2016",
    jobStartDate: "26-03-2024",
    service: "Internal Auditor",
  },
  {
    id: 61,
    firstname: "Maéna",
    lastname: "Makeswell",
    state: "Nord-Pas-de-Calais",
    street: "International",
    city: "Hénin-Beaumont",
    zip: "62254 CEDEX",
    birthDate: "01-08-2018",
    jobStartDate: "07-12-2023",
    service: "Nurse Practicioner",
  },
  {
    id: 62,
    firstname: "Judicaël",
    lastname: "Collishaw",
    state: "Bretagne",
    street: "Ramsey",
    city: "Quimper",
    zip: "29327 CEDEX",
    birthDate: "13-08-2022",
    jobStartDate: "08-03-2024",
    service: "Nurse",
  },
  {
    id: 63,
    firstname: "Kuí",
    lastname: "Varley",
    state: "Provence-Alpes-Côte d'Azur",
    street: "Susan",
    city: "Istres",
    zip: "13802 CEDEX",
    birthDate: "26-06-2022",
    jobStartDate: "31-01-2024",
    service: "Administrative Assistant III",
  },
  {
    id: 64,
    firstname: "Véronique",
    lastname: "Muglestone",
    state: "Île-de-France",
    street: "Burning Wood",
    city: "Rungis",
    zip: "94598 CEDEX 2",
    birthDate: "08-03-2022",
    jobStartDate: "21-02-2024",
    service: "VP Sales",
  },
  {
    id: 65,
    firstname: "Lyséa",
    lastname: "Beinke",
    state: "Bretagne",
    street: "Toban",
    city: "Redon",
    zip: "35605 CEDEX",
    birthDate: "06-09-2022",
    jobStartDate: "12-01-2024",
    service: "Structural Engineer",
  },
  {
    id: 66,
    firstname: "Kévina",
    lastname: "Orpen",
    state: "Île-de-France",
    street: "Vermont",
    city: "Paris 16",
    zip: "75220 CEDEX 16",
    birthDate: "23-01-2015",
    jobStartDate: "15-01-2024",
    service: "VP Accounting",
  },
  {
    id: 67,
    firstname: "Börje",
    lastname: "Clemencet",
    state: "Aquitaine",
    street: "Messerschmidt",
    city: "Mont-de-Marsan",
    zip: "40025 CEDEX",
    birthDate: "17-07-2014",
    jobStartDate: "13-07-2024",
    service: "Budget/Accounting Analyst III",
  },
  {
    id: 68,
    firstname: "Miléna",
    lastname: "Kirrage",
    state: "Aquitaine",
    street: "Blaine",
    city: "Agen",
    zip: "47912 CEDEX 9",
    birthDate: "06-05-2018",
    jobStartDate: "24-12-2023",
    service: "Software Test Engineer IV",
  },
  {
    id: 69,
    firstname: "Maëlys",
    lastname: "Vearncombe",
    state: "Bretagne",
    street: "Moland",
    city: "La Gacilly",
    zip: "56209 CEDEX",
    birthDate: "19-10-2016",
    jobStartDate: "20-03-2024",
    service: "Financial Advisor",
  },
  {
    id: 70,
    firstname: "Mårten",
    lastname: "Winter",
    state: "Île-de-France",
    street: "Dorton",
    city: "Melun",
    zip: "77014 CEDEX",
    birthDate: "11-04-2024",
    jobStartDate: "07-04-2024",
    service: "Associate Professor",
  },
  {
    id: 71,
    firstname: "Estée",
    lastname: "Calwell",
    state: "Bretagne",
    street: "7th",
    city: "Rennes",
    zip: "35704 CEDEX 7",
    birthDate: "20-05-2017",
    jobStartDate: "24-03-2024",
    service: "Senior Cost Accountant",
  },
  {
    id: 72,
    firstname: "Desirée",
    lastname: "Gullan",
    state: "Île-de-France",
    street: "Carioca",
    city: "Montesson",
    zip: "78364 CEDEX",
    birthDate: "24-12-2018",
    jobStartDate: "13-06-2024",
    service: "Engineer II",
  },
  {
    id: 73,
    firstname: "Mélanie",
    lastname: "Glaserman",
    state: "Provence-Alpes-Côte d'Azur",
    street: "Lillian",
    city: "Salon-de-Provence",
    zip: "13662 CEDEX",
    birthDate: "14-07-2023",
    jobStartDate: "20-08-2024",
    service: "Account Coordinator",
  },
  {
    id: 74,
    firstname: "Pénélope",
    lastname: "Sherrock",
    state: "Île-de-France",
    street: "Granby",
    city: "Rungis",
    zip: "94575 CEDEX 2",
    birthDate: "11-11-2014",
    jobStartDate: "12-12-2023",
    service: "Recruiter",
  },
  {
    id: 75,
    firstname: "Lorène",
    lastname: "Niblock",
    state: "Provence-Alpes-Côte d'Azur",
    street: "Anderson",
    city: "Toulon",
    zip: "83077 CEDEX 9",
    birthDate: "07-08-2017",
    jobStartDate: "05-07-2024",
    service: "Biostatistician II",
  },
  {
    id: 76,
    firstname: "Erwéi",
    lastname: "Laughnan",
    state: "Centre",
    street: "Ronald Regan",
    city: "Blois",
    zip: "41919 CEDEX 9",
    birthDate: "21-04-2021",
    jobStartDate: "05-05-2024",
    service: "Environmental Specialist",
  },
  {
    id: 77,
    firstname: "Valérie",
    lastname: "Kobu",
    state: "Île-de-France",
    street: "Eastlawn",
    city: "Nanterre",
    zip: "92024 CEDEX",
    birthDate: "20-02-2014",
    jobStartDate: "13-06-2024",
    service: "Associate Professor",
  },
  {
    id: 78,
    firstname: "Nuó",
    lastname: "Barrus",
    state: "Franche-Comté",
    street: "Gina",
    city: "Besançon",
    zip: "25024 CEDEX",
    birthDate: "03-11-2022",
    jobStartDate: "30-06-2024",
    service: "Senior Financial Analyst",
  },
  {
    id: 79,
    firstname: "Mélina",
    lastname: "Jobbins",
    state: "Provence-Alpes-Côte d'Azur",
    street: "Surrey",
    city: "Marseille",
    zip: "13568 CEDEX 02",
    birthDate: "10-04-2017",
    jobStartDate: "20-05-2024",
    service: "Operator",
  },
  {
    id: 80,
    firstname: "Maëlyss",
    lastname: "O'Neil",
    state: "Île-de-France",
    street: "Norway Maple",
    city: "Ivry-sur-Seine",
    zip: "94852 CEDEX",
    birthDate: "20-01-2019",
    jobStartDate: "24-05-2024",
    service: "Health Coach I",
  },
  {
    id: 81,
    firstname: "Estée",
    lastname: "Rubinsky",
    state: "Île-de-France",
    street: "Katie",
    city: "Coulommiers",
    zip: "77529 CEDEX",
    birthDate: "13-12-2023",
    jobStartDate: "14-01-2024",
    service: "Structural Analysis Engineer",
  },
  {
    id: 82,
    firstname: "Thérèse",
    lastname: "Strutley",
    state: "Auvergne",
    street: "Stephen",
    city: "Montluçon",
    zip: "03104 CEDEX",
    birthDate: "04-12-2014",
    jobStartDate: "16-07-2024",
    service: "Dental Hygienist",
  },
  {
    id: 83,
    firstname: "Garçon",
    lastname: "Hardin",
    state: "Île-de-France",
    street: "Helena",
    city: "Guyancourt",
    zip: "78280",
    birthDate: "22-12-2023",
    jobStartDate: "09-11-2023",
    service: "Biostatistician II",
  },
  {
    id: 84,
    firstname: "Noëlla",
    lastname: "Normanvill",
    state: "Provence-Alpes-Côte d'Azur",
    street: "Weeping Birch",
    city: "Marseille",
    zip: "13464 CEDEX 16",
    birthDate: "19-02-2014",
    jobStartDate: "05-07-2024",
    service: "Associate Professor",
  },
  {
    id: 85,
    firstname: "Maëly",
    lastname: "Magrannell",
    state: "Île-de-France",
    street: "Chive",
    city: "Colombes",
    zip: "92715 CEDEX",
    birthDate: "12-08-2016",
    jobStartDate: "19-11-2023",
    service: "Legal Assistant",
  },
  {
    id: 86,
    firstname: "Lài",
    lastname: "Hussy",
    state: "Île-de-France",
    street: "Clove",
    city: "Taverny",
    zip: "95251 CEDEX",
    birthDate: "24-09-2013",
    jobStartDate: "14-04-2024",
    service: "Marketing Manager",
  },
  {
    id: 87,
    firstname: "Maéna",
    lastname: "Goodyer",
    state: "Île-de-France",
    street: "School",
    city: "Chelles",
    zip: "77504 CEDEX",
    birthDate: "03-04-2018",
    jobStartDate: "18-09-2023",
    service: "Community Outreach Specialist",
  },
  {
    id: 88,
    firstname: "Gaïa",
    lastname: "Von Helmholtz",
    state: "Nord-Pas-de-Calais",
    street: "Farmco",
    city: "Lille",
    zip: "59859 CEDEX",
    birthDate: "17-04-2015",
    jobStartDate: "29-07-2024",
    service: "Web Designer I",
  },
  {
    id: 89,
    firstname: "Marlène",
    lastname: "Van Schafflaer",
    state: "Île-de-France",
    street: "Banding",
    city: "Aulnay-sous-Bois",
    zip: "93604 CEDEX",
    birthDate: "17-05-2023",
    jobStartDate: "02-01-2024",
    service: "Financial Advisor",
  },
  {
    id: 90,
    firstname: "Örjan",
    lastname: "Mothersole",
    state: "Bretagne",
    street: "Westridge",
    city: "Rennes",
    zip: "35047 CEDEX 9",
    birthDate: "08-04-2023",
    jobStartDate: "13-02-2024",
    service: "Account Representative II",
  },
  {
    id: 91,
    firstname: "Aimée",
    lastname: "Al Hirsi",
    state: "Île-de-France",
    street: "Onsgard",
    city: "Montesson",
    zip: "78364 CEDEX",
    birthDate: "08-02-2013",
    jobStartDate: "22-06-2024",
    service: "VP Quality Control",
  },
  {
    id: 92,
    firstname: "Maëlla",
    lastname: "Niesegen",
    state: "Île-de-France",
    street: "Browning",
    city: "Paris La Défense",
    zip: "92036 CEDEX",
    birthDate: "26-05-2013",
    jobStartDate: "28-01-2024",
    service: "Community Outreach Specialist",
  },
  {
    id: 93,
    firstname: "Marie-josée",
    lastname: "Keith",
    state: "Bretagne",
    street: "Rutledge",
    city: "Saint-Malo",
    zip: "35409 CEDEX",
    birthDate: "16-09-2019",
    jobStartDate: "07-02-2024",
    service: "Assistant Professor",
  },
  {
    id: 94,
    firstname: "Táng",
    lastname: "Mansfield",
    state: "Aquitaine",
    street: "Birchwood",
    city: "Bordeaux",
    zip: "33090 CEDEX",
    birthDate: "15-11-2022",
    jobStartDate: "01-11-2023",
    service: "Research Associate",
  },
  {
    id: 95,
    firstname: "Lén",
    lastname: "Hatch",
    state: "Bretagne",
    street: "Hoard",
    city: "Rennes",
    zip: "35076 CEDEX 9",
    birthDate: "15-03-2019",
    jobStartDate: "08-12-2023",
    service: "Research Assistant I",
  },
  {
    id: 96,
    firstname: "Thérèsa",
    lastname: "Lashbrook",
    state: "Île-de-France",
    street: "Merchant",
    city: "Fresnes",
    zip: "94264 CEDEX",
    birthDate: "23-02-2015",
    jobStartDate: "29-07-2024",
    service: "Help Desk Operator",
  },
  {
    id: 97,
    firstname: "Hélèna",
    lastname: "Bamber",
    state: "Centre",
    street: "Elmside",
    city: "Orléans",
    zip: "45063 CEDEX 2",
    birthDate: "31-08-2016",
    jobStartDate: "20-09-2023",
    service: "Professor",
  },
  {
    id: 98,
    firstname: "Bérénice",
    lastname: "Caton",
    state: "Aquitaine",
    street: "Hooker",
    city: "Hendaye",
    zip: "64704 CEDEX",
    birthDate: "17-10-2020",
    jobStartDate: "18-10-2023",
    service: "Engineer II",
  },
  {
    id: 99,
    firstname: "Clémence",
    lastname: "Piola",
    state: "Aquitaine",
    street: "Clemons",
    city: "Arcachon",
    zip: "33314 CEDEX",
    birthDate: "18-02-2018",
    jobStartDate: "22-01-2024",
    service: "Database Administrator II",
  },
  {
    id: 100,
    firstname: "Hélène",
    lastname: "Binch",
    state: "Bretagne",
    street: "Bunker Hill",
    city: "Redon",
    zip: "35605 CEDEX",
    birthDate: "20-06-2021",
    jobStartDate: "23-12-2023",
    service: "Help Desk Technician",
  },
];
